export const Types = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_ERROR: 'LOGIN_ERROR',
    USER_LOGOUT: 'USER_LOGOUT',

    FORGOT_REQUEST: 'FORGOT_REQUEST',
    FORGOT_SUCCESS: 'FORGOT_SUCCESS',
    FORGOT_ERROR: 'FORGOT_ERROR',

    RESET_REQUEST: 'RESET_REQUEST',
    RESET_SUCCESS: 'RESET_SUCCESS',
    RESET_ERROR: 'RESET_ERROR',

    ALERT_ERROR: 'ALERT_ERROR',
    ALERT_SUCCESS: 'ALERT_SUCCESS',
    ALERT_WARNING: 'ALERT_WARNING',
    ALERT_INFO: 'ALERT_INFO',
    ALERT_DEFAULT: 'ALERT_DEFAULT',
    ALERT_CLEAR: 'ALERT_CLEAR',

    NAVIGATION_LABEL: 'NAVIGATION_LABEL',

    USERS_REQUEST: 'USERS_REQUEST',
    USERS_SUCCESS: 'USERS_SUCCESS',
    USERS_ERROR: 'USERS_ERROR',

    USER_ADD_REQUEST: 'USER_ADD_REQUEST',
    USER_ADD_SUCCESS: 'USER_ADD_SUCCESS',
    USER_ADD_ERROR: 'USER_ADD_ERROR',

    ESL_REQUEST: 'ESL_REQUEST',
    ESL_SUCCESS: 'ESL_SUCCESS',
    ESL_ERROR: 'ESL_ERROR',

    ESL_ADD_REQUEST: 'ESL_ADD_REQUEST',
    ESL_ADD_SUCCESS: 'ESL_ADD_SUCCESS',
    ESL_ADD_ERROR: 'ESL_ADD_ERROR',

    STORE_REQUEST: 'STORE_REQUEST',
    STORE_SUCCESS: 'STORE_SUCCESS',
    STORE_ERROR: 'STORE_ERROR',

    STORE_ADD_REQUEST: 'STORE_ADD_REQUEST',
    STORE_ADD_SUCCESS: 'STORE_ADD_SUCCESS',
    STORE_ADD_ERROR: 'STORE_ADD_ERROR',

    CPE_REQUEST: 'CPE_REQUEST',
    CPE_SUCCESS: 'CPE_SUCCESS',
    CPE_ERROR: 'CPE_ERROR',

}